labs13-handy-app/Backend

api/server.js
Fixes # (not having a server)
sharanjit is setting up the port in index.js so it hasn't been tested yet. We will test it when she sets it up.
=> setting up server

api/server.js, index.js
- [ x ] Server is up and running on PORT 5000
=> API is up and running

api/server.js, package-lock.json
=> catch removed from server.js

api/server.js, index.js
=> Created migrations

auth-route/register-model.js, auth-route/register.js
Collaborating with front end to get users in DB with login
=> refactored register route, added register model

auth-route/register.js
trying to fix bug while adding user to database
=> fixing bug on register route

api/server.js, data-routes/projects.js, data-routes/users.js
Creates endpoint to render users and projects associated with them.
=> created users by id route created endpoint for get by id

data-routes/users.js, resources/payment/stripe.js
Creates endpoint for stripe transfers
=> endpoint for stripe transfer

data-routes/projects.js
Columns were renamed in tables, needed to update endpoints to reflect changes
=> updates endpoints to reflect data columns

data/migrations/20190531133451_handyapp.js
Adds a table to the knex schema for a homeowner to be able to give feedback to a service provider. 
=> Created table for homeowner feedback on a contractor

api/server.js, data-routes/feedback.js
Creates a route and endpoints for CRUD operations on the feedback table
=> added route and endpoints for feedback

data-routes/users.js
=> restricted middlware added to put route

data-routes/feedback.js
Adds an endpoint so that you can see the reviews based on the contractor ID. The array comes back with all of the information about a contractor and a list of all the reviews inside of the array
=> added endpoint for getting review by contractor id

data-routes/users.js
Allows a picture to be uploaded by a user for their proflie
=> configured cloudinary endpoint on users

auth-route/register.js
=> removed brackets around user object

data-routes/projects.js
Puts a join on the endpoint project by ID so the user can see more information about the contractor making the bid
=> refactored endpoint with join to show more information

data-routes/feedback.js
Fixed bug that threw error when getting profile of contractor if their was no feedback
=> removed constraint from endpoint that threw error if contractor didnt have feedback

data-routes/projects.js, data-routes/users.js, data/dbConfig.js, knexfile.js
=> Fixed images bug

resources/payment/stripe.js
-[x ] Incomplete/work-in-progress, PR is for discussion/feedback
=> error handling in charge route

resources/payment/stripe.js
=> add new customer route changes and charge route changes

resources/payment/stripe.js
removed source from endpoint trying to get charge to work correctly
=> removed source from endpoint for charge

resources/payment/stripe.js
=> made change on the charge endpoint, working locally

resources/payment/stripe.js
Switched around a few things to get transfer to work with front end
=> made small changes to stripe transfer endpoint

data-routes/users.js
=> rows added to projects array

data-routes/users.js
=> reversed projects array

data-routes/projects.js, data-routes/users.js
=> .rows added

data-routes/projects.js, data/dbConfig.js, knexfile.js
=> .rows removed from map()

data-routes/projects.js
=> Fields added to GET projects route

yarn.lock
Added yarn.lock file to try and fix failed deployment
=> adding yarn.lock file
